# TOKENS SHOULD BE STORED IN A .secrets.yaml file.

## ========================================================================== ##
common:
## ========================================================================== ##
    ## List of data paths to always add to the file resolver
    ## can be local or a path with credentials.
    search_paths :
        - "/opt/pixi/packages/s2gos-generator/resources/data"
        - "/opt/pixi/hypstar_data"

    local_fsspec_cache : "/tmp/fsspec_cache" # optional, defaults to "./tmp/fsspec_cache"
    credential_provider : "environment" # optional, {dynaconf, environment}

## ========================================================================== ##
generator:
## ========================================================================== ##
    # Data source paths, not included in the file-resolver.
    dataset:
        dem:
            name : "Copernicus-DEM-30" # optional
            crs : "EPSG:4326" # default/optional

            type : "zarr"
            path :
                value : "https://data.earthdatahub.destine.eu/copernicus-dem/GLO-30-v0.zarr"
                cid : "edh"
            variable_name : dsm # optional, recommended

        landcover:
            name : "ESA Worldcover 2021" # optional
            crs : "EPSG:4326" # default/optional

            type : "zarr"
            path :
                value: "s3://s2gos-input/worldcover.zarr"
                cid : "lc_ovh"
            variable_name : wc # optional, recommended

    files:
        material_config: "./materials.json" # can be resolved by file resolver
