site_name: s2gos-utils

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

nav:
  - Introduction: index.md
  - Setup: setup.md
  - Configuration: configuration.md
  - Data Access Layer: data_access_layer.md
  - Credentials: credentials.md
  - API Reference:
    - Scene Description: api/scene_description.md
    - Paths: api/paths.md