#!/usr/bin/env python3
"""Unpack a scene data bundle and write the settings file that points at it.

A bundle is a tar.gz holding the scene inputs that cannot be fetched automatically —
DEM and landcover tiles, building footprints, mesh assets, material spectra — none of
which is in git. This unpacks one into the repo and generates `s2gos_settings.yaml`,
after which the example runs. Roads, the ephemeris and eradiate's atmosphere data are
downloaded on first run and are not part of the bundle:

    python3 scripts/setup_scene_bundle.py san_rossore_icos_bundle.tar.gz
    pixi run --frozen -e dev python examples/san_rossore_icos.py

The data lands in `s2gos_data/` next to this checkout, and nothing outside it and
`s2gos_settings.yaml` is ever written. An existing settings file is moved aside to
`s2gos_settings.yaml.backup` rather than overwritten; `.secrets.yaml` is never touched.

Standard library only, so it works before the pixi environment is built.
"""

from __future__ import annotations

import os
import shutil
import sys
import tarfile
import tempfile
from pathlib import Path

INDEX_DIR = "packages/s2gos-generator/resources/data"

REPO = Path(__file__).resolve().parent.parent
DEST = REPO / "s2gos_data"
SETTINGS = REPO / "s2gos_settings.yaml"
BACKUP = REPO / "s2gos_settings.yaml.backup"


class SetupError(Exception):
    """Anything that should stop setup with a readable message."""


def log(msg: str) -> None:
    print(msg, flush=True)


def extract(archive: Path, dest: Path) -> None:
    """Extract to a temp dir beside the destination, then swap into place.

    `filter="data"` is what keeps the extraction inside the staging directory: it
    refuses absolute paths, `..` escapes, links and device files. An existing tree is
    replaced only once the new one is complete, so an interrupted run leaves the old
    data intact.
    """
    if not hasattr(tarfile, "data_filter"):
        raise SetupError("Python 3.12 or newer is needed to unpack the bundle safely")

    dest.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".s2gos_bundle_", dir=dest.parent))

    try:
        try:
            with tarfile.open(archive, "r:gz") as tar:
                tar.extractall(staging, filter="data")
        except (tarfile.TarError, EOFError, OSError) as exc:
            raise SetupError(f"could not unpack {archive.name}: {exc}") from exc

        roots = list(staging.iterdir())
        if len(roots) != 1 or not roots[0].is_dir() or roots[0].name != dest.name:
            raise SetupError(
                f"expected a single '{dest.name}' directory in the archive — "
                "is this a scene bundle?"
            )

        unpacked = roots[0]
        files = [p for p in unpacked.rglob("*") if p.is_file()]
        total = sum(p.stat().st_size for p in files)
        log(f"  {len(files)} files, {total / 2**20:.0f} MiB")

        if dest.exists():
            previous = dest.with_name(dest.name + ".previous")
            shutil.rmtree(previous, ignore_errors=True)
            os.replace(dest, previous)
            os.replace(unpacked, dest)
            shutil.rmtree(previous, ignore_errors=True)
        else:
            os.replace(unpacked, dest)
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def settings_yaml(dest: Path) -> str:
    """The settings file for an unpacked bundle, with absolute paths."""
    assets = dest / "assets"
    search_paths = [
        assets / "tower",
        assets / "forest",
        assets / "wytham_mitsuba",
        assets / "materials",
    ]
    listed = "\n".join(f'        - "{p}"' for p in search_paths)

    return f"""# Generated by scripts/setup_scene_bundle.py — edit freely.
# Paths point into the unpacked scene bundle at {dest}.
# Secrets belong in .secrets.yaml, never here.

common:
    search_paths:
{listed}

generator:
    dataset:
        dem:
            name : "Copernicus-DEM-30"
            crs : "EPSG:4326"
            type : "indexed-geotiff"
            root_directory : "{dest / "datasets" / "dem"}"
            index_path : "{REPO / INDEX_DIR / "dem_index.feather"}"
            path_column : "path_dem"
            variable_name : elevation

        landcover:
            name : "ESA Worldcover 2021"
            crs : "EPSG:4326"
            type : "indexed-geotiff"
            root_directory : "{dest / "datasets" / "landcover"}"
            index_path : "{REPO / INDEX_DIR / "landcover_index.feather"}"
            path_column : "path_lc"
            variable_name : landcover

    files:
        material_config: "{assets / "materials" / "materials.json"}"
        building_tiles: "{dest / "datasets" / "buildings" / "OpenBuildingsMap"}"
"""


def write_settings(dest: Path) -> None:
    """Write the settings file, preserving any existing one as a backup."""
    if SETTINGS.exists():
        shutil.move(str(SETTINGS), str(BACKUP))
        log(f"  kept your previous settings as {BACKUP.name}")

    SETTINGS.write_text(settings_yaml(dest))
    log(f"  wrote {SETTINGS.name}")


def main() -> int:
    if len(sys.argv) != 2 or sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        print("usage: python3 scripts/setup_scene_bundle.py <bundle.tar.gz>")
        return 0 if len(sys.argv) == 2 else 2

    bundle = Path(sys.argv[1])

    try:
        if not bundle.exists():
            raise SetupError(f"bundle not found: {bundle}")

        log(f"Unpacking {bundle.name} -> {DEST}")
        extract(bundle.resolve(), DEST)

        log("Writing settings ...")
        write_settings(DEST)

        log("\nDone. Run the example with:")
        log("  pixi run --frozen -e dev python examples/san_rossore_icos.py")
        return 0

    except SetupError as exc:
        print(f"\nerror: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
